package com.aryout.database.jdbc.adapters;

import java.sql.*;

/**
 * Created by 97390 on 11/15/2017.
 */
public class StatementAdapter implements Statement {
    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        return null;
    }

    @Override
    public int executeUpdate(String sql) throws SQLException {
        return 0;
    }

    @Override
    public void close() throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public int getMaxFieldSize() throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public void setMaxFieldSize(int max) throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public int getMaxRows() throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public void setMaxRows(int max) throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public void setEscapeProcessing(boolean enable) throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public int getQueryTimeout() throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public void setQueryTimeout(int seconds) throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public void cancel() throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public SQLWarning getWarnings() throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public void clearWarnings() throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public void setCursorName(String name) throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public boolean execute(String sql) throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public ResultSet getResultSet() throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public int getUpdateCount() throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public boolean getMoreResults() throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public void setFetchDirection(int direction) throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public int getFetchDirection() throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public void setFetchSize(int rows) throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public int getFetchSize() throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public int getResultSetConcurrency() throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public int getResultSetType() throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public void addBatch(String sql) throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public void clearBatch() throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public int[] executeBatch() throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public Connection getConnection() throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public boolean getMoreResults(int current) throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public ResultSet getGeneratedKeys() throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public boolean execute(String sql, String[] columnNames) throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public int getResultSetHoldability() throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public boolean isClosed() throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public void setPoolable(boolean poolable) throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public boolean isPoolable() throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public void closeOnCompletion() throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public boolean isCloseOnCompletion() throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException {
        throw new SQLException("Unsupported");
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        throw new SQLException("Unsupported");
    }
}
